-- PromptAstra — Supabase schema for the security_events table.
-- Run this in the Supabase SQL editor before starting the app.
-- Columns match exactly what the FastAPI backend and Flask frontend read/write.

create table if not exists public.security_events (
    id               bigint generated by default as identity primary key,
    prompt           text        not null,
    decision         text        not null,          -- ALLOW | REVIEW | BLOCK
    risk_score       integer     not null default 0,-- 0-100 security risk score
    threat_category  text,                           -- e.g. PROMPT_INJECTION
    reason           text,
    rule_score       double precision default 0,     -- 0-1 fraction
    ml_score         double precision default 0,     -- 0-1 fraction
    created_at       timestamptz not null default now()
);

-- Helpful index for the "newest first" log/monitor queries.
create index if not exists security_events_created_at_idx
    on public.security_events (created_at desc);

-- ---------------------------------------------------------------------------
-- Row Level Security (RLS)
-- ---------------------------------------------------------------------------
-- The service_role key bypasses RLS, so if the servers use that key you can
-- leave RLS enabled with no policies. If you use the anon key instead, add
-- policies that permit select/insert. Example (permissive — tighten for prod):
--
-- alter table public.security_events enable row level security;
-- create policy "allow read"  on public.security_events for select using (true);
-- create policy "allow write" on public.security_events for insert with check (true);
